version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: linkpages_postgres
    restart: always
    environment:
      POSTGRES_USER: linkuser
      POSTGRES_PASSWORD: linkpass
      POSTGRES_DB: linkpagesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - linkpages-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: linkpages_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - linkpages-net

networks:
  linkpages-net:

volumes:
  pgdata:
